/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login endpoint - creates user if not exists and returns auth token.
         *
         *     - **email**: User email address
         *
         *     Returns auth token and user info.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current authenticated user info.
         *
         *     Requires Bearer token in Authorization header.
         */
        get: operations["get_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout endpoint - invalidates the auth token.
         *
         *     Requires Bearer token in Authorization header.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workflows
         * @description List all workflows
         */
        get: operations["list_workflows_api_v1_workflows_get"];
        put?: never;
        /**
         * Create Workflow
         * @description Create a new workflow
         */
        post: operations["create_workflow_api_v1_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow
         * @description Get a workflow by ID
         */
        get: operations["get_workflow_api_v1_workflows__workflow_id__get"];
        /**
         * Update Workflow
         * @description Update an existing workflow
         */
        put: operations["update_workflow_api_v1_workflows__workflow_id__put"];
        post?: never;
        /**
         * Delete Workflow
         * @description Delete a workflow
         */
        delete: operations["delete_workflow_api_v1_workflows__workflow_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{workflow_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Workflow */
        post: operations["execute_workflow_api_v1_workflows__workflow_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Document
         * @description Upload a document and automatically trigger vectorization.
         */
        post: operations["upload_document_api_v1_knowledge__kb_id__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List all documents in a knowledge base.
         */
        get: operations["list_documents_api_v1_knowledge__kb_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete a document from a knowledge base.
         */
        delete: operations["delete_document_api_v1_knowledge__kb_id__documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}/process/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process Document
         * @description Process a document: parse, chunk, embed, and store to ChromaDB.
         */
        post: operations["process_document_api_v1_knowledge__kb_id__process__doc_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Status */
        get: operations["get_task_status_api_v1_knowledge_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Documents
         * @description Search for relevant chunks in a knowledge base.
         */
        get: operations["search_documents_api_v1_knowledge__kb_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge Base Info */
        get: operations["get_knowledge_base_info_api_v1_knowledge__kb_id__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Bases */
        get: operations["list_knowledge_bases_api_v1_knowledge_get"];
        put?: never;
        /** Create Knowledge Base */
        post: operations["create_knowledge_base_api_v1_knowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/{kb_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Knowledge Base */
        delete: operations["delete_knowledge_base_api_v1_knowledge__kb_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skills
         * @description List all available skills.
         *
         *     Returns a list of skill summaries sorted by updated_at (newest first).
         *     Admin users see all skills, regular users only see their own.
         */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        /**
         * Create Skill
         * @description Create a new skill.
         *
         *     - **name**: Skill name (used as folder name)
         *     - **content**: Complete SKILL.md file content
         *
         *     The skill name must be unique, lowercase, and contain only letters,
         *     numbers, and hyphens. Cannot start or end with hyphen.
         */
        post: operations["create_skill_api_v1_skills_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Skill
         * @description Get detailed information about a specific skill.
         *
         *     - **name**: Skill name (path parameter)
         */
        get: operations["get_skill_api_v1_skills__name__get"];
        /**
         * Update Skill
         * @description Update an existing skill's SKILL.md content.
         *
         *     - **name**: Skill name (path parameter, cannot be changed)
         *     - **content**: New SKILL.md file content
         *
         *     Note: The skill name cannot be changed via update. To rename,
         *     delete and recreate the skill.
         */
        put: operations["update_skill_api_v1_skills__name__put"];
        post?: never;
        /**
         * Delete Skill
         * @description Delete a skill and all its contents.
         *
         *     - **name**: Skill name to delete
         *
         *     This permanently removes the skill folder and all files within it.
         */
        delete: operations["delete_skill_api_v1_skills__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Skill
         * @description Execute a skill with the provided inputs.
         *
         *     - **name**: Skill name to execute
         *     - **inputs**: Dictionary of input variable values
         *
         *     Returns a Server-Sent Events (SSE) stream with the following event types:
         *     - `thought`: Execution status updates (validation, substitution, retrieval, generation)
         *     - `token`: LLM-generated content chunks
         *     - `citation`: Source citations from knowledge base retrieval
         *     - `done`: Completion marker with status
         */
        post: operations["run_skill_api_v1_skills__name__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Completions
         * @description SSE streaming chat completion endpoint.
         *
         *     Supports simple chat, RAG-enhanced chat, and workflow execution.
         */
        post: operations["chat_completions_api_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List chat sessions for the current user.
         */
        get: operations["list_sessions_api_v1_chat_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session History
         * @description Get chat history for a session.
         */
        get: operations["get_session_history_api_v1_chat_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a chat session and its history.
         */
        delete: operations["delete_session_api_v1_chat_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable User */
        post: operations["disable_user_api_v1_admin_users__user_id__disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable User */
        post: operations["enable_user_api_v1_admin_users__user_id__enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_v1_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_v1_knowledge__kb_id__upload_post */
        Body_upload_document_api_v1_knowledge__kb_id__upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * ChatRequest
         * @description Chat request model for SSE streaming chat endpoint.
         *
         *     - session_id: Unique session identifier
         *     - message: User's input message
         *     - workflow_id: Optional workflow to execute
         *     - kb_id: Optional knowledge base ID for RAG-enhanced responses
         *     - user_id: DEPRECATED - User ID is now obtained from authentication token
         */
        ChatRequest: {
            /**
             * Session Id
             * @description Unique session identifier for conversation continuity
             */
            session_id: string;
            /**
             * Message
             * @description User's input message
             */
            message: string;
            /**
             * Workflow Id
             * @description Optional workflow ID
             */
            workflow_id?: string | null;
            /**
             * Kb Id
             * @description Optional knowledge base ID for RAG retrieval
             */
            kb_id?: string | null;
            /**
             * User Id
             * @description DEPRECATED: User ID is obtained from auth token. This field is ignored.
             */
            user_id?: string | null;
        };
        /**
         * DocumentListResponse
         * @description Response model for document list.
         */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentResponse"][];
            /** Total */
            total: number;
        };
        /**
         * DocumentResponse
         * @description Document response model for API.
         */
        DocumentResponse: {
            /** Id */
            id: string;
            /** Kb Id */
            kb_id: string;
            /** Filename */
            filename: string;
            status: components["schemas"]["DocumentStatus"];
            /** File Size */
            file_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Task Id */
            task_id?: string | null;
        };
        /**
         * DocumentStatus
         * @description Document processing status.
         * @enum {string}
         */
        DocumentStatus: "pending" | "processing" | "completed" | "failed";
        /**
         * GraphData
         * @description Vue Flow graph data structure
         */
        GraphData: {
            /**
             * Nodes
             * @description Vue Flow nodes
             */
            nodes?: {
                [key: string]: unknown;
            }[];
            /**
             * Edges
             * @description Vue Flow edges
             */
            edges?: {
                [key: string]: unknown;
            }[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeBase
         * @description Knowledge base model.
         */
        KnowledgeBase: {
            /**
             * Id
             * @description Knowledge base unique ID
             */
            id: string;
            /**
             * Name
             * @description Knowledge base name
             */
            name: string;
            /**
             * Document Count
             * @description Number of documents
             * @default 0
             */
            document_count: number;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        /**
         * KnowledgeBaseCreate
         * @description Model for creating a new knowledge base.
         */
        KnowledgeBaseCreate: {
            /**
             * Name
             * @description Knowledge base name
             */
            name: string;
        };
        /**
         * KnowledgeBaseListResponse
         * @description Response model for knowledge base list.
         */
        KnowledgeBaseListResponse: {
            /** Items */
            items: components["schemas"]["KnowledgeBase"][];
            /** Total */
            total: number;
        };
        /**
         * LoginRequest
         * @description Login request model.
         */
        LoginRequest: {
            /**
             * Email
             * @description User email address
             */
            email: string;
        };
        /**
         * LoginResponse
         * @description Login response model.
         */
        LoginResponse: {
            /**
             * Token
             * @description Authentication token
             */
            token: string;
            /** @description User information */
            user: components["schemas"]["UserResponse"];
        };
        /**
         * LogoutResponse
         * @description Logout response model.
         */
        LogoutResponse: {
            /**
             * Success
             * @description Whether logout was successful
             */
            success: boolean;
        };
        /**
         * SkillCreateRequest
         * @description Request model for creating a new skill.
         */
        SkillCreateRequest: {
            /**
             * Name
             * @description Skill name (will be used as folder name)
             */
            name: string;
            /**
             * Content
             * @description Complete SKILL.md file content
             */
            content: string;
        };
        /**
         * SkillDetail
         * @description Complete skill information including prompt content.
         */
        SkillDetail: {
            /**
             * Name
             * @description Skill name (unique, lowercase, alphanumeric + hyphens)
             */
            name: string;
            /**
             * Description
             * @description Description of skill functionality and use cases
             */
            description: string;
            /**
             * License
             * @description License name (e.g., MIT)
             */
            license?: string | null;
            /**
             * Metadata
             * @description Arbitrary metadata key-value pairs
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Inputs
             * @description Input variable definitions
             */
            inputs?: components["schemas"]["SkillInput"][] | null;
            /**
             * Knowledge Base
             * @description Associated knowledge base ID or name
             */
            knowledge_base?: string | null;
            /** @description Model configuration for execution */
            model?: components["schemas"]["SkillModelConfig"] | null;
            /**
             * User Id
             * @description Owner user ID (reserved for future use)
             */
            user_id?: string | null;
            /**
             * Prompt
             * @description Markdown body (the prompt template)
             */
            prompt: string;
            /**
             * Raw Content
             * @description Complete SKILL.md file content
             */
            raw_content: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * SkillInput
         * @description Input variable definition for a skill.
         */
        SkillInput: {
            /**
             * Name
             * @description Variable name used in prompt templates like {{name}}
             */
            name: string;
            /**
             * Label
             * @description UI display label for the input
             */
            label: string;
            /**
             * Type
             * @description Input type: text or textarea
             * @default text
             * @enum {string}
             */
            type: "text" | "textarea";
            /**
             * Required
             * @description Whether this input is required
             * @default false
             */
            required: boolean;
            /**
             * Default
             * @description Default value if not provided
             */
            default?: string | null;
            /**
             * Description
             * @description Help text describing the input
             */
            description?: string | null;
        };
        /**
         * SkillListResponse
         * @description Response model for skill list endpoint.
         */
        SkillListResponse: {
            /** Skills */
            skills: components["schemas"]["SkillSummary"][];
            /** Total */
            total: number;
        };
        /**
         * SkillModelConfig
         * @description LLM model configuration for skill execution.
         */
        SkillModelConfig: {
            /**
             * Temperature
             * @description Sampling temperature (0-2)
             * @default 0.7
             */
            temperature: number | null;
            /**
             * Max Tokens
             * @description Maximum tokens to generate
             * @default 2000
             */
            max_tokens: number | null;
        };
        /**
         * SkillRunRequest
         * @description Request model for executing a skill.
         */
        SkillRunRequest: {
            /**
             * Inputs
             * @description Input variable values (name -> value)
             */
            inputs?: {
                [key: string]: string;
            };
        };
        /**
         * SkillSummary
         * @description Lightweight skill info for list views.
         */
        SkillSummary: {
            /**
             * Name
             * @description Skill name (unique identifier)
             */
            name: string;
            /**
             * Description
             * @description Short description of skill purpose
             */
            description: string;
            /**
             * Has Inputs
             * @description Whether skill has defined inputs
             * @default false
             */
            has_inputs: boolean;
            /**
             * Has Knowledge Base
             * @description Whether skill has associated knowledge base
             * @default false
             */
            has_knowledge_base: boolean;
            /**
             * Updated At
             * Format: date-time
             * @description Last modification timestamp
             */
            updated_at: string;
        };
        /**
         * SkillUpdateRequest
         * @description Request model for updating an existing skill.
         */
        SkillUpdateRequest: {
            /**
             * Content
             * @description Complete SKILL.md file content (name cannot be changed)
             */
            content: string;
        };
        /** UserActionResponse */
        UserActionResponse: {
            /**
             * Success
             * @description Whether action was successful
             */
            success: boolean;
            /**
             * Message
             * @description Action result message
             */
            message: string;
        };
        /** UserListItem */
        UserListItem: {
            /**
             * Id
             * @description User ID
             */
            id: number;
            /**
             * Email
             * @description User email
             */
            email: string;
            /**
             * Role
             * @description User role (admin or user)
             */
            role: string;
            /**
             * Is Active
             * @description Whether user is active
             */
            is_active: boolean;
            /**
             * Created At
             * @description Creation timestamp ISO format
             */
            created_at: string;
        };
        /** UserListResponse */
        UserListResponse: {
            /**
             * Users
             * @description List of users
             */
            users: components["schemas"]["UserListItem"][];
            /**
             * Total
             * @description Total number of users
             */
            total: number;
        };
        /**
         * UserResponse
         * @description User response model.
         */
        UserResponse: {
            /**
             * Id
             * @description User ID
             */
            id: number;
            /**
             * Email
             * @description User email
             */
            email: string;
            /**
             * Role
             * @description User role (admin or user)
             */
            role: string;
            /**
             * Is Active
             * @description Whether user is active
             */
            is_active: boolean;
            /**
             * Created At
             * @description Creation timestamp ISO format
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Workflow
         * @description Complete workflow model with ID and timestamps
         */
        Workflow: {
            /**
             * Name
             * @description Workflow name
             */
            name: string;
            /**
             * Description
             * @description Workflow description
             */
            description?: string | null;
            /** @description Vue Flow graph data */
            graph_data?: components["schemas"]["GraphData"];
            /**
             * Id
             * @description Unique workflow identifier
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        /**
         * WorkflowCreate
         * @description Model for creating a new workflow
         */
        WorkflowCreate: {
            /**
             * Name
             * @description Workflow name
             */
            name: string;
            /**
             * Description
             * @description Workflow description
             */
            description?: string | null;
            /** @description Vue Flow graph data */
            graph_data?: components["schemas"]["GraphData"];
        };
        /**
         * WorkflowExecuteRequest
         * @description Request body for workflow execution.
         */
        WorkflowExecuteRequest: {
            /**
             * Input
             * @description Workflow input text
             */
            input: string;
        };
        /**
         * WorkflowList
         * @description Response model for workflow list
         */
        WorkflowList: {
            /** Items */
            items: components["schemas"]["Workflow"][];
            /** Total */
            total: number;
        };
        /**
         * WorkflowUpdate
         * @description Model for updating an existing workflow
         */
        WorkflowUpdate: {
            /**
             * Name
             * @description Workflow name
             */
            name?: string | null;
            /**
             * Description
             * @description Workflow description
             */
            description?: string | null;
            /** @description Vue Flow graph data */
            graph_data?: components["schemas"]["GraphData"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    list_workflows_api_v1_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowList"];
                };
            };
        };
    };
    create_workflow_api_v1_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_v1_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_workflow_api_v1_workflows__workflow_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workflow_api_v1_workflows__workflow_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_workflow_api_v1_workflows__workflow_id__execute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowExecuteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_knowledge__kb_id__upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_knowledge__kb_id__upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_knowledge__kb_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_knowledge__kb_id__documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_document_api_v1_knowledge__kb_id__process__doc_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_knowledge_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_documents_api_v1_knowledge__kb_id__search_get: {
        parameters: {
            query: {
                /** @description Search query */
                query: string;
                /** @description Number of top results to return */
                top_k?: number;
            };
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_base_info_api_v1_knowledge__kb_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_bases_api_v1_knowledge_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBaseListResponse"];
                };
            };
        };
    };
    create_knowledge_base_api_v1_knowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeBaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeBase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_knowledge_base_api_v1_knowledge__kb_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
        };
    };
    create_skill_api_v1_skills_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_skill_api_v1_skills__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_skill_api_v1_skills__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skill_api_v1_skills__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_skill_api_v1_skills__name__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_completions_api_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_chat_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_session_history_api_v1_chat_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_chat_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    disable_user_api_v1_admin_users__user_id__disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enable_user_api_v1_admin_users__user_id__enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_v1_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
